#https://github.com/Sunnysaloni
#https://t.me/Noob_to_pro_hack
#https://t.me/Sunny_ki_duniya

name: Docker Image CI

on:
  push:
    branches: [ "2r" ]
  pull_request:
    branches: [ "2r" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
